version: '3.9'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"

  image_processor:
    build: ../image_processor
    command: bundle exec ruby start.rb
    volumes:
      - ../image_processor:/myapp
    depends_on:
      - rabbitmq
